import { type Applicant } from "@/components/ui/applicant_table";

export const allApplicants: Applicant[] = [
  {
    id: "1",
    name: "Yusuf Ibrahim",
    category: "Technology",
    desiredCareer: "Junior Developer",
    yearsExp: 2,
    services: ["Resume", "Mock"],
    submitted: "2026-06-01",
    status: "Awaiting",
    email: "yusuf.ibrahim@email.com",
    phone: "+1 (416) 555-0188",
    careerGoal: "Break into full-stack web development",
    industryInterest: "Technology",
    education: "Bachelor's in Computer Science",
    skills: ["JavaScript", "React", "Node.js"],
  },
  {
    id: "2",
    name: "Tariq Mahmood",
    category: "Technology",
    desiredCareer: "Systems Engineer",
    yearsExp: 5,
    services: ["Mock Interview", "Mentorship"],
    submitted: "2026-06-07",
    status: "Awaiting",
    email: "tariq.mahmood@email.com",
    phone: "+1 (416) 555-0319",
    careerGoal: "Transition from engineering to product management",
    industryInterest: "Technology",
    education: "Bachelor's in Electrical Engineering",
    skills: ["Systems Engineering", "Python", "SQL", "Agile"],
  },
  {
    id: "3",
    name: "Amira Osman",
    category: "Marketing",
    desiredCareer: "Brand Strategist",
    yearsExp: 3,
    services: ["Resume"],
    submitted: "2026-06-03",
    status: "Matched",
    email: "amira.osman@email.com",
    phone: "+1 (416) 555-0210",
    careerGoal: "Lead brand campaigns at a major agency",
    industryInterest: "Marketing",
    education: "Bachelor's in Communications",
    skills: ["Branding", "Content Strategy", "SEO"],
  },
  {
    id: "4",
    name: "Bilal Chaudhry",
    category: "Finance",
    desiredCareer: "Financial Analyst",
    yearsExp: 4,
    services: ["Mock", "Mentorship"],
    submitted: "2026-06-05",
    status: "Awaiting",
    email: "bilal.chaudhry@email.com",
    phone: "+1 (416) 555-0142",
    careerGoal: "Move into investment banking",
    industryInterest: "Finance",
    education: "Bachelor's in Finance",
    skills: ["Excel", "Financial Modeling", "Valuation"],
  },
  {
    id: "5",
    name: "Hana Malek",
    category: "Healthcare",
    desiredCareer: "Registered Nurse",
    yearsExp: 6,
    services: ["Resume", "Mentorship"],
    submitted: "2026-06-02",
    status: "Matched",
    email: "hana.malek@email.com",
    phone: "+1 (416) 555-0177",
    careerGoal: "Specialize in pediatric nursing",
    industryInterest: "Healthcare",
    education: "Bachelor's in Nursing",
    skills: ["Patient Care", "Triage", "EMR"],
  },
  {
    id: "6",
    name: "Salma Diallo",
    category: "Legal",
    desiredCareer: "Paralegal",
    yearsExp: 1,
    services: ["Mock"],
    submitted: "2026-06-08",
    status: "Awaiting",
    email: "salma.diallo@email.com",
    phone: "+1 (416) 555-0263",
    careerGoal: "Become a corporate lawyer",
    industryInterest: "Legal",
    education: "Bachelor's in Political Science",
    skills: ["Legal Research", "Drafting", "Case Management"],
  },
];