import { Resend } from 'resend'

if (!process.env.RESEND_API_KEY) {
  throw new Error('Missing RESEND_API_KEY environment variable')
}

const resendClient = new Resend(process.env.RESEND_API_KEY)

/**
 * Gets upper initials from a name for the email avatar fallback
 */
function getInitials(name) {
  if (!name || name === "No Name Set") return "U";
  return name
    .split(" ")
    .map((part) => part[0])
    .slice(0, 2)
    .join("")
    .toUpperCase();
}

/**
 * Sends a custom styled verification email using the Ummah Professionals template.
 * @param {string} email - The user's email address.
 * @param {string} name - The user's full name.
 * @param {string} verificationUrl - The action link generated by supabaseAdmin.auth.admin.generateLink().
 * @param {string} [avatarUrl] - Optional URL for the user's profile picture.
 */
export async function sendVerificationEmail(email, name, verificationUrl, avatarUrl = null) {
  const initials = getInitials(name);

  // Profile Picture HTML rendering
  const pfpHtml = avatarUrl
    ? `<img src="${avatarUrl}" alt="${name}" style="width:64px;height:64px;border-radius:50%;object-fit:cover;border:3px solid #ffffff;box-shadow:0 2px 6px rgba(0,0,0,0.15);" />`
    : `<div style="width:64px;height:64px;border-radius:50%;background:#e0f2fe;color:#007CA6;font-size:22px;font-weight:bold;line-height:64px;text-align:center;margin:0 auto;border:3px solid #ffffff;box-shadow:0 2px 8px rgba(0,0,0,0.1);">${initials}</div>`;

  // Injects the raw HTML string and swaps out the template values dynamically
  const emailHtml = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Confirm Your Email</title>
    </head>
    <body style="margin:0;padding:0;background-color:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#1e293b;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;padding:40px 20px;">
        <tr>
          <td align="center">
            <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:16px;overflow:hidden;border:1px solid #e2e8f0;box-shadow:0 4px 12px rgba(0,0,0,0.05);">
              <!-- Header -->
              <tr>
                <td align="center" style="background:#007CA6;padding:36px 30px;">
                  <h1 style="margin:0;color:#ffffff;font-size:26px;font-weight:700;letter-spacing:-0.5px;"> Ummah Professionals </h1>
                  <p style="margin:6px 0 0;color:#e0f2fe;font-size:14px;font-weight:500;"> Professional Muslim Networking Platform </p>
                </td>
              </tr>
              <!-- Body -->
              <tr>
                <td style="padding:40px 40px 32px 40px;">
                  <!-- Avatar -->
                  <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
                    <tr>
                      <td align="center" style="padding-bottom:20px;">
                        ${pfpHtml}
                      </td>
                    </tr>
                  </table>
                  <h2 style="margin:0 0 16px 0;font-size:22px;font-weight:700;color:#0f172a;text-align:center;"> Welcome, ${name}! </h2>
                  <p style="font-size:15px;line-height:1.6;color:#334155;margin:0 0 24px 0;text-align:center;"> Thank you for creating your Ummah Professionals account. Please verify your email address by clicking the button below. </p>
                  <table role="presentation" cellpadding="0" cellspacing="0" align="center" style="margin:28px auto;">
                    <tr>
                      <td align="center" bgcolor="#007CA6" style="border-radius:9999px;">
                        <a href="${verificationUrl}" style="display:inline-block;padding:14px 32px;color:#ffffff;text-decoration:none;font-size:14px;font-weight:600;"> Confirm Email Address </a>
                      </td>
                    </tr>
                  </table>
                  <p style="font-size:13px;line-height:1.6;color:#64748b;margin-top:28px;text-align:center;"> If the button above doesn't work, copy and paste this link into your browser: </p>
                  <p style="word-break:break-all;font-size:13px;color:#007CA6;text-align:center;margin:8px 0 0 0;"> ${verificationUrl} </p>
                  <hr style="border:none;border-top:1px solid #e2e8f0;margin:32px 0 24px 0;">
                  <p style="font-size:13px;line-height:1.6;color:#94a3b8;margin:0;text-align:center;"> If you didn't create an account with Ummah Professionals, you can safely ignore this email. </p>
                </td>
              </tr>
              <!-- Footer -->
              <tr>
                <td style="background:#f8fafc;padding:24px 30px;text-align:center;border-top:1px solid #f1f5f9;">
                  <p style="margin:0 0 4px 0;font-size:13px;font-weight:700;color:#0f172a;"> Ummah Professionals </p>
                  <p style="margin:0;font-size:12px;color:#64748b;line-height:1.5;"> Connecting Muslim professionals through careers, mentorship, and meaningful opportunities. </p>
                  <p style="margin-top:16px;font-size:11px;color:#999999;"> This is an automated email. Please do not reply. </p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </body>
    </html>
  `

  return await resendClient.emails.send({
    from: 'Ummah Professionals <onboarding@resend.dev>',
    to: "interns.ummah.professional@gmail.com",
    subject: 'Confirm Your Email - Ummah Professionals',
    html: emailHtml,
  })
}