import { Resend } from 'resend'

if (!process.env.RESEND_API_KEY) {
  throw new Error('Missing RESEND_API_KEY environment variable')
}

const resendClient = new Resend(process.env.RESEND_API_KEY)

/**
 * Sends a custom styled verification email using the Ummah Professionals template.
 * @param {string} email - The user's email address.
 * @param {string} name - The user's full name.
 * @param {string} verificationUrl - The action link generated by supabaseAdmin.auth.admin.generateLink().
 */
export async function sendVerificationEmail(email, name, verificationUrl) {
  // Injects the raw HTML string and swaps out the template values dynamically
  const emailHtml = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <title>Confirm Your Email</title>
    </head>
    <body style="margin:0;padding:0;background-color:#f4f6f8;font-family:Arial,Helvetica,sans-serif;color:#333333;">
      <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#f4f6f8;padding:40px 20px;">
        <tr>
          <td align="center">
            <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 4px 12px rgba(0,0,0,0.08);">
              <!-- Header -->
              <tr>
                <td align="center" style="background:#0f766e;padding:40px 30px;">
                  <h1 style="margin:0;color:#ffffff;font-size:30px;font-weight:bold;"> Ummah Professionals </h1>
                  <p style="margin:12px 0 0;color:#dff8f5;font-size:16px;"> Professional Muslim Networking Platform </p>
                </td>
              </tr>
              <!-- Body -->
              <tr>
                <td style="padding:50px 45px;">
                  <h2 style="margin-top:0;font-size:28px;color:#222222;"> Welcome, ${name}! </h2>
                  <p style="font-size:16px;line-height:1.8;margin-bottom:25px;"> Thank you for creating your Ummah Professionals account. To complete your registration and activate your account, please verify your email address by clicking the button below. </p>
                  <table role="presentation" cellpadding="0" cellspacing="0" align="center" style="margin:35px auto;">
                    <tr>
                      <td align="center" bgcolor="#0f766e" style="border-radius:8px;">
                        <a href="${verificationUrl}" style="display:inline-block;padding:16px 34px;color:#ffffff;text-decoration:none;font-size:16px;font-weight:bold;"> Confirm Email Address </a>
                      </td>
                    </tr>
                  </table>
                  <p style="font-size:15px;line-height:1.8;color:#555555;"> If the button above doesn't work, copy and paste this link into your browser: </p>
                  <p style="word-break:break-all;font-size:14px;color:#0f766e;"> ${verificationUrl} </p>
                  <hr style="border:none;border-top:1px solid #e5e7eb;margin:40px 0;">
                  <p style="font-size:15px;line-height:1.7;color:#555555;"> If you didn't create an account with Ummah Professionals, you can safely ignore this email. No account will be activated unless this email address is confirmed. </p>
                </td>
              </tr>
              <!-- Footer -->
              <tr>
                <td style="background:#f8fafc;padding:30px;text-align:center;">
                  <p style="margin:0 0 10px;font-size:15px;font-weight:bold;color:#222;"> Ummah Professionals </p>
                  <p style="margin:0;font-size:13px;color:#666666;line-height:1.6;"> Connecting Muslim professionals through careers, mentorship, and meaningful opportunities. </p>
                  <p style="margin-top:20px;font-size:12px;color:#999999;"> This is an automated email. Please do not reply. </p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </body>
    </html>
  `

  return await resendClient.emails.send({
    from: 'Ummah Professionals <onboarding@resend.dev>', // Update to your custom domain later
    to: email,
    subject: 'Confirm Your Email - Ummah Professionals',
    html: emailHtml,
  })
}
